### ISSUE TITLE
Erro ao subir o aplicativo pós atualização

### ISSUE THREAD

**Issue by andersonvass** [rictom/rede-cnpj#25]
Bom dia,

Atualizei os scritps hoje (git pull) e estou tendo erro ao subir a aplicação. Reinstalei os pacotes do requirements e atualizei o pip. Além disso acrescentei no arquivo requirements.txt os pacotes: spacy, textract, langdetect

Segue o erro:

**_(base) [root@s1410 rede]# python rede.py
Carregando rede_sqlite_cnpj
Utilizando rede_sqlite_cnpj como rede_relacionamentos.
/opt/anaconda3/lib/python3.10/site-packages/flask_limiter/extension.py:293: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/coinf/aplicacoes/rede/rede-cnpj/rede/rede.py", line 64, in <module>
    api_key_validas = [k.strip() for k in config.config['API'].get('api_keys', '').split(',')]
  File "/opt/anaconda3/lib/python3.10/configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'API'
(base) [root@s1410 rede]#_**

**Comment by rictom** [comment]
Oi @andersonvass,

Você deve estar usando uma versão antiga do arquivo de configuração rede.ini. Na versão mais nova tem uma seção api
[API]
api_cnpj=1
api_caminhos=1
api_keys=
Copiando isso pro arquivo de configuração, deve funcionar

**Comment by andersonvass** [comment]
Obrigado @rictom pelo rápido retorno,

Coloquei a seção que faltava e atualizei o anaconda (conda update --all) e o pip ( pip install --upgrade pip). 

Agora estou tendo esse erro aqui:


**_se) [root@s1410 rede]# python rede.py
Traceback (most recent call last):
  File "/opt/coinf/aplicacoes/rede/rede-cnpj/rede/rede.py", line 12, in <module>
    import flask_limiter #pip install Flask-Limiter
  File "/opt/anaconda3/lib/python3.10/site-packages/flask_limiter/__init__.py", line 4, in <module>
    from .errors import RateLimitExceeded
  File "/opt/anaconda3/lib/python3.10/site-packages/flask_limiter/errors.py", line 6, in <module>
    from .typing import Optional
  File "/opt/anaconda3/lib/python3.10/site-packages/flask_limiter/typing.py", line 14, in <module>
    from typing_extensions import ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
(base) [root@s1410 rede]#_**

tentei instalar o   'typing_extensions' e recebo o seguinte:

 **_pip install typing_extensions
Requirement already satisfied: typing_extensions in /opt/anaconda3/lib/python3.10/site-packages (4.7.1)
DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(base) [root@s1410 rede]#_**

Alguma sugestão?

**Comment by rictom** [comment]
Eu recomendaria vc começar de novo. Se vc está no linux, nem precisa instalar o anaconda (isso é bom no Windows, mas no linux não precisa). Em qualquer caso, mesmo com o anaconda, é recomendado criar um ambiente virtual para rodar o projeto específico, assim vc não bagunça as versões de python ou de bibliotecas que outras coisas que estão rodando nessa máquina. Segue algum tutorial como o https://www.freecodecamp.org/news/how-to-setup-virtual-environments-in-python/ (sem anaconda) ou https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment (com anaconda)

**Comment by andersonvass** [comment]
Bom dia @rictom .

Refiz a instalação criando o ambiente virtual no anaconda e deu certo.

Muito Obrigado pela ajuda.

Até mais
